
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightEQUALnonassocISEQUALDEQUALnonassocLESSGREATERLESSEQUALGREATEREQUALleftPLUSMINUSleftTIMESDIVIDEleftLBLOCKRBLOCKleftLPARENRPARENAPOSTROPHE BREAK CASE CLASS COLON COMMENTS COMMENTS_C99 CONST DEQUAL DISTINT DIVIDE DO DOT ELSE EQUAL FALSE FOR GREATER GREATEREQUAL ID IDVAR IF ISEQUAL LBLOCK LBRACKET LESS LESSEQUAL LPAREN MAIN MINUS MINUSEQUAL MINUSMINUS NUM PLUS PLUSEQUAL PLUSPLUS PRINT QUOTES RBLOCK RBRACKET RETURN RPAREN SEMI STATIC STRING SWITCH TIMES TRUE VAR VOID WHILEcondition : expressioncondition : expression relation expressionrelation : EQUALrelation : ISEQUALrelation : DEQUALrelation : LESSrelation : GREATERrelation : LESSEQUALrelation : GREATEREQUALexpression : termexpression : addingOperator termexpression : expression addingOperator termaddingOperator : PLUSaddingOperator : MINUSterm : factorterm : term multiplyingOperator factormultiplyingOperator : TIMESmultiplyingOperator : DIVIDEfactor : IDfactor : NUMfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'PLUS':([0,2,3,5,8,9,10,11,13,14,15,16,17,18,19,23,24,25,26,27,28,],[6,6,-10,-15,-19,-20,6,6,-3,-4,-5,-6,-7,-8,-9,-11,6,6,-12,-16,-21,]),'MINUS':([0,2,3,5,8,9,10,11,13,14,15,16,17,18,19,23,24,25,26,27,28,],[7,7,-10,-15,-19,-20,7,7,-3,-4,-5,-6,-7,-8,-9,-11,7,7,-12,-16,-21,]),'ID':([0,4,6,7,10,11,12,13,14,15,16,17,18,19,20,21,22,],[8,8,-13,-14,8,8,8,-3,-4,-5,-6,-7,-8,-9,8,-17,-18,]),'NUM':([0,4,6,7,10,11,12,13,14,15,16,17,18,19,20,21,22,],[9,9,-13,-14,9,9,9,-3,-4,-5,-6,-7,-8,-9,9,-17,-18,]),'LPAREN':([0,4,6,7,10,11,12,13,14,15,16,17,18,19,20,21,22,],[10,10,-13,-14,10,10,10,-3,-4,-5,-6,-7,-8,-9,10,-17,-18,]),'$end':([1,2,3,5,8,9,23,25,26,27,28,],[0,-1,-10,-15,-19,-20,-11,-2,-12,-16,-21,]),'EQUAL':([2,3,5,8,9,23,26,27,28,],[13,-10,-15,-19,-20,-11,-12,-16,-21,]),'ISEQUAL':([2,3,5,8,9,23,26,27,28,],[14,-10,-15,-19,-20,-11,-12,-16,-21,]),'DEQUAL':([2,3,5,8,9,23,26,27,28,],[15,-10,-15,-19,-20,-11,-12,-16,-21,]),'LESS':([2,3,5,8,9,23,26,27,28,],[16,-10,-15,-19,-20,-11,-12,-16,-21,]),'GREATER':([2,3,5,8,9,23,26,27,28,],[17,-10,-15,-19,-20,-11,-12,-16,-21,]),'LESSEQUAL':([2,3,5,8,9,23,26,27,28,],[18,-10,-15,-19,-20,-11,-12,-16,-21,]),'GREATEREQUAL':([2,3,5,8,9,23,26,27,28,],[19,-10,-15,-19,-20,-11,-12,-16,-21,]),'RPAREN':([3,5,8,9,23,24,26,27,28,],[-10,-15,-19,-20,-11,28,-12,-16,-21,]),'TIMES':([3,5,8,9,23,26,27,28,],[21,-15,-19,-20,21,21,-16,-21,]),'DIVIDE':([3,5,8,9,23,26,27,28,],[22,-15,-19,-20,22,22,-16,-21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'condition':([0,],[1,]),'expression':([0,10,11,],[2,24,25,]),'term':([0,4,10,11,12,],[3,23,3,3,26,]),'addingOperator':([0,2,10,11,24,25,],[4,12,4,4,12,12,]),'factor':([0,4,10,11,12,20,],[5,5,5,5,5,27,]),'relation':([2,],[11,]),'multiplyingOperator':([3,23,26,],[20,20,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> condition","S'",1,None,None,None),
  ('condition -> expression','condition',1,'p_condition','sintactico.py',42),
  ('condition -> expression relation expression','condition',3,'p_condition1','sintactico.py',46),
  ('relation -> EQUAL','relation',1,'p_relation1','sintactico.py',50),
  ('relation -> ISEQUAL','relation',1,'p_relation2','sintactico.py',54),
  ('relation -> DEQUAL','relation',1,'p_relation3','sintactico.py',58),
  ('relation -> LESS','relation',1,'p_relation4','sintactico.py',62),
  ('relation -> GREATER','relation',1,'p_relation5','sintactico.py',66),
  ('relation -> LESSEQUAL','relation',1,'p_relation6','sintactico.py',70),
  ('relation -> GREATEREQUAL','relation',1,'p_relation7','sintactico.py',74),
  ('expression -> term','expression',1,'p_expression1','sintactico.py',79),
  ('expression -> addingOperator term','expression',2,'p_expression2','sintactico.py',83),
  ('expression -> expression addingOperator term','expression',3,'p_expression3','sintactico.py',87),
  ('addingOperator -> PLUS','addingOperator',1,'p_addingOperator1','sintactico.py',91),
  ('addingOperator -> MINUS','addingOperator',1,'p_addingOperator2','sintactico.py',95),
  ('term -> factor','term',1,'p_term1','sintactico.py',99),
  ('term -> term multiplyingOperator factor','term',3,'p_term2','sintactico.py',103),
  ('multiplyingOperator -> TIMES','multiplyingOperator',1,'p_multiplyingOperator1','sintactico.py',107),
  ('multiplyingOperator -> DIVIDE','multiplyingOperator',1,'p_multiplyingOperator2','sintactico.py',111),
  ('factor -> ID','factor',1,'p_factor1','sintactico.py',115),
  ('factor -> NUM','factor',1,'p_factor2','sintactico.py',119),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor3','sintactico.py',123),
]
